import { Wallpaper } from "../types/wallpaper";
import { Category } from "../types/category";

function img(seed: string, w: number, h: number) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const CATEGORIES: Category[] = [
  { id: "cat-1", name: "Nature & Landscapes", slug: "nature", description: "Mountains, oceans, misty forests, and cosmic skies.", image: img("wallora-nature", 600, 400), wallpaperCount: 4 },
  { id: "cat-2", name: "Cars & Automotive", slug: "cars", description: "Hypercars, GT3 track weapons, retro classics, and rain slicks.", image: img("wallora-cars", 600, 400), wallpaperCount: 3 },
  { id: "cat-3", name: "Anime & Manga", slug: "anime", description: "Cinematic sunsets, quiet city streets, and expressive character art.", image: img("wallora-anime", 600, 400), wallpaperCount: 3 },
  { id: "cat-4", name: "Gaming & Cyberpunk", slug: "gaming", description: "Neon alleys, dark setup glows, pixel castles, and retro rigs.", image: img("wallora-gaming", 600, 400), wallpaperCount: 4 },
  { id: "cat-5", name: "Minimal & Clean", slug: "minimal", description: "Soft gradients, calm dunes, linen textures, and breathing room.", image: img("wallora-minimal", 600, 400), wallpaperCount: 3 },
  { id: "cat-6", name: "Space & Cosmos", slug: "space", description: "Orbital stations, dreamy galaxies, starfields, and distant planets.", image: img("wallora-space", 600, 400), wallpaperCount: 2 },
  { id: "cat-7", name: "Aesthetic & Mood", slug: "aesthetic", description: "Pink dunes, soft grain, dreamy lighting, and editorial tone.", image: img("wallora-aesthetic", 600, 400), wallpaperCount: 2 },
  { id: "cat-8", name: "Technology & Code", slug: "technology", description: "Macro circuits, dark terminals, futuristic cities, and synth.", image: img("wallora-tech", 600, 400), wallpaperCount: 3 },
];

export const MOCK_WALLPAPERS: Wallpaper[] = [
  {
    id: "midnight-porsche",
    title: "Midnight Porsche — Tokyo Rain",
    description: "Rain slicked street in Tokyo at midnight with Porsche 911 GT3.",
    imageUrl: img("wallora-porsche", 1920, 1080),
    thumbnailUrl: img("wallora-porsche", 600, 338),
    width: 1920,
    height: 1080,
    orientation: "landscape",
    deviceType: "desktop",
    downloads: 48210,
    isAI: false,
    categoryId: "cat-2",
    category: { id: "cat-2", name: "Cars & Automotive", slug: "cars" },
    author: { id: "user-1", name: "Kaito Mori" },
    createdAt: "2026-09-10T12:00:00Z",
  },
  {
    id: "dune-silence",
    title: "Dune Silence",
    description: "Calm desert dunes under soft morning sky.",
    imageUrl: img("wallora-dune", 1080, 1920),
    thumbnailUrl: img("wallora-dune", 600, 1066),
    width: 1080,
    height: 1920,
    orientation: "portrait",
    deviceType: "phone",
    downloads: 31120,
    isAI: false,
    categoryId: "cat-5",
    category: { id: "cat-5", name: "Minimal & Clean", slug: "minimal" },
    author: { id: "user-2", name: "Amara Diallo" },
    createdAt: "2026-09-18T08:30:00Z",
  },
  {
    id: "anime-sunset",
    title: "Anime Sunset Over the Valley",
    description: "Warm clouds and golden hills in hand-drawn style.",
    imageUrl: img("wallora-anime1", 1920, 1080),
    thumbnailUrl: img("wallora-anime1", 600, 338),
    width: 1920,
    height: 1080,
    orientation: "landscape",
    deviceType: "desktop",
    downloads: 55400,
    isAI: false,
    categoryId: "cat-3",
    category: { id: "cat-3", name: "Anime & Manga", slug: "anime" },
    author: { id: "user-3", name: "Yuki Tanaka" },
    createdAt: "2026-08-28T16:45:00Z",
  },
  {
    id: "forest-fog",
    title: "Fog in the Pines",
    description: "Dense coniferous forest shrouded in cool morning mist.",
    imageUrl: img("wallora-forest", 1080, 1920),
    thumbnailUrl: img("wallora-forest", 600, 1066),
    width: 1080,
    height: 1920,
    orientation: "portrait",
    deviceType: "phone",
    downloads: 28900,
    isAI: false,
    categoryId: "cat-1",
    category: { id: "cat-1", name: "Nature & Landscapes", slug: "nature" },
    author: { id: "user-4", name: "Jonas Weber" },
    createdAt: "2026-09-02T06:15:00Z",
  },
  {
    id: "cyberpunk-alley",
    title: "Cyberpunk Alley",
    description: "Neon lit alleyway in futuristic metropolis.",
    imageUrl: img("wallora-cyber", 3440, 1440),
    thumbnailUrl: img("wallora-cyber", 600, 251),
    width: 3440,
    height: 1440,
    orientation: "ultrawide",
    deviceType: "ultrawide",
    downloads: 39800,
    isAI: true,
    categoryId: "cat-4",
    category: { id: "cat-4", name: "Gaming & Cyberpunk", slug: "gaming" },
    author: { id: "user-5", name: "Wallora AI" },
    createdAt: "2026-09-12T22:10:00Z",
  },
  {
    id: "pink-dunes",
    title: "Pink Aesthetic Dunes",
    description: "Pastel sand dunes in twilight gradient.",
    imageUrl: img("wallora-pink", 1080, 1920),
    thumbnailUrl: img("wallora-pink", 600, 1066),
    width: 1080,
    height: 1920,
    orientation: "portrait",
    deviceType: "phone",
    downloads: 22140,
    isAI: false,
    categoryId: "cat-7",
    category: { id: "cat-7", name: "Aesthetic & Mood", slug: "aesthetic" },
    author: { id: "user-6", name: "Sofia Marques" },
    createdAt: "2026-09-20T14:20:00Z",
  },
  {
    id: "orbit-station",
    title: "Orbital Drift",
    description: "Deep space station overlooking blue planet curvature.",
    imageUrl: img("wallora-space1", 3840, 2160),
    thumbnailUrl: img("wallora-space1", 600, 338),
    width: 3840,
    height: 2160,
    orientation: "landscape",
    deviceType: "desktop",
    downloads: 18400,
    isAI: false,
    categoryId: "cat-6",
    category: { id: "cat-6", name: "Space & Cosmos", slug: "space" },
    author: { id: "user-7", name: "Elena Vostok" },
    createdAt: "2026-09-05T09:40:00Z",
  },
  {
    id: "future-city",
    title: "Future City — Dawn Line",
    description: "Glass skybridges and sunrise reflections on mega-structures.",
    imageUrl: img("wallora-future", 3440, 1440),
    thumbnailUrl: img("wallora-future", 600, 251),
    width: 3440,
    height: 1440,
    orientation: "ultrawide",
    deviceType: "ultrawide",
    downloads: 19800,
    isAI: true,
    categoryId: "cat-8",
    category: { id: "cat-8", name: "Technology & Code", slug: "technology" },
    author: { id: "user-5", name: "Wallora AI" },
    createdAt: "2026-09-15T05:50:00Z",
  },
];

